[package]
name = "jose_analyseur"
version = "0.1.0"
authors = ["Johan Planchon <johan.planchon@simplx.fr>"]
edition = "2018"
license = "MIT"

[dependencies]
nom = "6.1.2"
slog = "2.7.0"
thiserror = "1.0.24"
